#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

OPENRECALL_CONDA_ENV="${OPENRECALL_CONDA_ENV:-MyRecall}"
OPENRECALL_PYTHON="${OPENRECALL_PYTHON:-python}"
OPENRECALL_USE_CONDA="${OPENRECALL_USE_CONDA:-auto}"
OPENRECALL_LOG_FILE="${OPENRECALL_LOG_FILE:-}"

OPENRECALL_HOST="${OPENRECALL_HOST:-127.0.0.1}"
OPENRECALL_PORT="${OPENRECALL_PORT:-8083}"

export OPENRECALL_API_URL="${OPENRECALL_API_URL:-http://$OPENRECALL_HOST:$OPENRECALL_PORT/api}"
export OPENRECALL_DATA_DIR="${OPENRECALL_DATA_DIR:-$ROOT_DIR/.openrecall_client_data}"
export OPENRECALL_DEBUG="${OPENRECALL_DEBUG:-true}"
export OPENRECALL_CAPTURE_INTERVAL="${OPENRECALL_CAPTURE_INTERVAL:-10}"
export OPENRECALL_UPLOAD_TIMEOUT="${OPENRECALL_UPLOAD_TIMEOUT:-180}"
export OPENRECALL_PRIMARY_MONITOR_ONLY="${OPENRECALL_PRIMARY_MONITOR_ONLY:-true}"
export OPENRECALL_CLIENT_SAVE_LOCAL_SCREENSHOTS="${OPENRECALL_CLIENT_SAVE_LOCAL_SCREENSHOTS:-false}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"

echo "OpenRecall client starting..."
echo "  data_dir=$OPENRECALL_DATA_DIR"
echo "  api_url=$OPENRECALL_API_URL"
echo "  debug=$OPENRECALL_DEBUG capture_interval=$OPENRECALL_CAPTURE_INTERVAL upload_timeout=$OPENRECALL_UPLOAD_TIMEOUT"

if [[ "$OPENRECALL_USE_CONDA" != "false" && "$OPENRECALL_USE_CONDA" != "0" ]] && command -v conda >/dev/null 2>&1; then
  if [[ -n "$OPENRECALL_LOG_FILE" ]]; then
    conda run -n "$OPENRECALL_CONDA_ENV" "$OPENRECALL_PYTHON" -u -m openrecall.client 2>&1 | tee -a "$OPENRECALL_LOG_FILE"
    exit $?
  fi
  exec conda run -n "$OPENRECALL_CONDA_ENV" "$OPENRECALL_PYTHON" -u -m openrecall.client
fi

if [[ -n "$OPENRECALL_LOG_FILE" ]]; then
  "$OPENRECALL_PYTHON" -u -m openrecall.client 2>&1 | tee -a "$OPENRECALL_LOG_FILE"
  exit $?
fi

exec "$OPENRECALL_PYTHON" -u -m openrecall.client
